Repository gear-tech/sails, pull requests merged in 2025-05, with the labels that each got.

#918 feat(sails-rs,sails-macro): Use stack buffer to optimize reply payloads
  rs/ethexe/macros-tests/tests/snapshots/program_insta__generates_ctors_meta_with_docs.snap
  rs/ethexe/macros-tests/tests/snapshots/program_insta__generates_handle_for_multiple_services_with_non_empty_routes.snap
  rs/ethexe/macros-tests/tests/snapshots/program_insta__generates_handle_for_services_with_unwrap_result.snap
  rs/ethexe/macros-tests/tests/snapshots/program_insta__generates_handle_for_single_service_with_non_empty_route.snap
  rs/ethexe/macros-tests/tests/snapshots/program_insta__generates_handle_with_crate_path.snap
  rs/ethexe/macros-tests/tests/snapshots/program_insta__generates_handle_with_gprogram_attributes.snap
  rs/ethexe/macros-tests/tests/snapshots/program_insta__generates_init_for_multiple_ctors.snap
  rs/ethexe/macros-tests/tests/snapshots/program_insta__generates_init_for_no_ctor.snap
  rs/ethexe/macros-tests/tests/snapshots/program_insta__generates_init_for_single_ctor.snap
  rs/ethexe/macros-tests/tests/snapshots/program_insta__generates_init_with_unwrap_result.snap
  rs/ethexe/macros-tests/tests/snapshots/service_insta__works_with_allow_attrs.snap
  rs/ethexe/macros-tests/tests/snapshots/service_insta__works_with_basics.snap
  rs/ethexe/macros-tests/tests/snapshots/service_insta__works_with_crate_path.snap
  rs/ethexe/macros-tests/tests/snapshots/service_insta__works_with_docs.snap
  rs/ethexe/macros-tests/tests/snapshots/service_insta__works_with_events.snap
  rs/ethexe/macros-tests/tests/snapshots/service_insta__works_with_export.snap
  rs/ethexe/macros-tests/tests/snapshots/service_insta__works_with_extends.snap
  rs/ethexe/macros-tests/tests/snapshots/service_insta__works_with_extends_and_lifetimes.snap
  rs/ethexe/macros-tests/tests/snapshots/service_insta__works_with_lifetimes_and_events.snap
  rs/ethexe/macros-tests/tests/snapshots/service_insta__works_with_lifetimes_and_generics.snap
  rs/ethexe/macros-tests/tests/snapshots/service_insta__works_with_methods_with_lifetimes.snap
  rs/ethexe/macros-tests/tests/snapshots/service_insta__works_with_reply_with_value.snap
  rs/ethexe/macros-tests/tests/snapshots/service_insta__works_with_special_lifetimes_and_events.snap
  rs/macros/core/src/program/mod.rs
  rs/macros/core/src/service/exposure.rs
  rs/macros/core/src/service/mod.rs
  rs/macros/core/tests/snapshots/gprogram__generates_async_main_with_handle_reply.snap
  rs/macros/core/tests/snapshots/gprogram__generates_ctors_meta_with_docs.snap
  rs/macros/core/tests/snapshots/gprogram__generates_handle_for_multiple_services_with_non_empty_routes.snap
  rs/macros/core/tests/snapshots/gprogram__generates_handle_for_services_with_unwrap_result.snap
  rs/macros/core/tests/snapshots/gprogram__generates_handle_for_single_service_with_non_empty_route.snap
  rs/macros/core/tests/snapshots/gprogram__generates_handle_with_crate_path.snap
  rs/macros/core/tests/snapshots/gprogram__generates_handle_with_gprogram_attributes.snap
  rs/macros/core/tests/snapshots/gprogram__generates_handle_with_payable.snap
  rs/macros/core/tests/snapshots/gprogram__generates_init_for_multiple_ctors.snap
  rs/macros/core/tests/snapshots/gprogram__generates_init_for_no_ctor.snap
  rs/macros/core/tests/snapshots/gprogram__generates_init_for_single_ctor.snap
  rs/macros/core/tests/snapshots/gprogram__generates_init_with_unwrap_result.snap
  rs/macros/core/tests/snapshots/gservice__works_with_allow_attrs.snap
  rs/macros/core/tests/snapshots/gservice__works_with_basics.snap
  rs/macros/core/tests/snapshots/gservice__works_with_crate_path.snap
  rs/macros/core/tests/snapshots/gservice__works_with_docs.snap
  rs/macros/core/tests/snapshots/gservice__works_with_events.snap
  rs/macros/core/tests/snapshots/gservice__works_with_export.snap
  rs/macros/core/tests/snapshots/gservice__works_with_extends.snap
  rs/macros/core/tests/snapshots/gservice__works_with_extends_and_lifetimes.snap
  rs/macros/core/tests/snapshots/gservice__works_with_lifetimes_and_events.snap
  rs/macros/core/tests/snapshots/gservice__works_with_lifetimes_and_generics.snap
  rs/macros/core/tests/snapshots/gservice__works_with_methods_with_lifetimes.snap
  rs/macros/core/tests/snapshots/gservice__works_with_reply_with_value.snap
  rs/macros/core/tests/snapshots/gservice__works_with_special_lifetimes_and_events.snap
  rs/macros/tests/gservice_tests.rs
  rs/src/gstd/ethexe.rs
  rs/src/gstd/events.rs
  rs/src/gstd/mod.rs
Labels: A2-mergeoncegreen

#920 feat: add Syscall struct, impl for wasm & tests
  README.md
  examples/demo/app/src/counter/mod.rs
  examples/demo/app/src/lib.rs
  examples/demo/app/src/value_fee/mod.rs
  examples/proxy/src/this_that/mod.rs
  examples/rmrk/catalog/app/src/lib.rs
  examples/rmrk/catalog/app/src/services/mod.rs
  examples/rmrk/resource/app/src/lib.rs
  examples/rmrk/resource/app/src/services/mod.rs
  rs/ethexe/macros-tests/tests/snapshots/program_insta__generates_handle_for_multiple_services_with_non_empty_routes.snap
  rs/ethexe/macros-tests/tests/snapshots/program_insta__generates_handle_for_services_with_unwrap_result.snap
  rs/ethexe/macros-tests/tests/snapshots/program_insta__generates_handle_for_single_service_with_non_empty_route.snap
  rs/macros/core/src/program/mod.rs
  rs/macros/core/tests/snapshots/gprogram__generates_handle_for_multiple_services_with_non_empty_routes.snap
  rs/macros/core/tests/snapshots/gprogram__generates_handle_for_services_with_unwrap_result.snap
  rs/macros/core/tests/snapshots/gprogram__generates_handle_for_single_service_with_non_empty_route.snap
  rs/src/gstd/mod.rs
  rs/src/gstd/syscalls.rs
  rs/src/prelude.rs
Labels: rust

#896 feat: Support program upgradability with gr_exit call to redirect message to new program
  Cargo.lock
  Cargo.toml
  README.md
  examples/redirect/Cargo.toml
  examples/redirect/app/Cargo.toml
  examples/redirect/app/build.rs
  examples/redirect/app/src/lib.rs
  examples/redirect/client/Cargo.toml
  examples/redirect/client/build.rs
  examples/redirect/client/redirect.idl
  examples/redirect/client/src/lib.rs
  examples/redirect/client/src/redirect_client.rs
  examples/redirect/proxy-client/Cargo.toml
  examples/redirect/proxy-client/build.rs
  examples/redirect/proxy-client/redirect_proxy.idl
  examples/redirect/proxy-client/src/lib.rs
  examples/redirect/proxy-client/src/redirect_proxy_client.rs
  examples/redirect/proxy/Cargo.toml
  examples/redirect/proxy/build.rs
  examples/redirect/proxy/src/lib.rs
  examples/redirect/tests/gtest.rs
  rs/Cargo.toml
  rs/ethexe/Cargo.lock
  rs/ethexe/Cargo.toml
  rs/src/gstd/calls.rs
  rs/src/gstd/message_future.rs
  rs/src/gstd/mod.rs
  rs/src/gtest/calls.rs
  rs/src/gtest/mod.rs
  rs/src/prelude.rs
Labels: rust

#933 feat(js): follow program upgrades
  .github/workflows/js-ci.yml
  .github/workflows/js-release.yml
  .gitignore
  js/CHANGELOG.md
  js/cli/package.json
  js/cli/src/app.ts
  js/cli/src/config.json
  js/cli/src/generate/index.ts
  js/cli/src/generate/service-gen.ts
  js/cli/test/__snapshots__/generator.test.js.snap
  js/cli/test/generator.test.js
  js/config.json
  js/example/package.json
  js/example/src/global.d.ts
  js/example/src/lib.ts
  js/example/src/main.ts
  js/jest.config.ts
  js/package.json
  js/parser/package.json
  js/scripts/test.sh
  js/src/transaction-builder.ts
  js/test/demo.test.ts
  js/types/package.json
  js/util/package.json
  lerna.json
  package.json
  yarn.lock
Labels: javascript
