Repository gear-tech/sails, pull requests merged in 2025-06, with the labels that each got.

#947 feat: introduce Builder to generate IDL and client from program
  Cargo.lock
  Cargo.toml
  examples/demo/app/tests/fixture/mod.rs
  examples/demo/app/tests/gclient.rs
  examples/demo/app/tests/gtest.rs
  examples/demo/client/Cargo.toml
  examples/demo/client/build.rs
  examples/demo/client/demo_client.idl
  examples/demo/client/src/demo_client.rs
  examples/demo/client/src/lib.rs
  examples/no-svcs-prog/wasm/Cargo.toml
  examples/no-svcs-prog/wasm/build.rs
  examples/no-svcs-prog/wasm/no_svcs_prog.idl
  examples/no-svcs-prog/wasm/src/client.rs
  examples/no-svcs-prog/wasm/src/no_svcs_prog.rs
  examples/no-svcs-prog/wasm/tests/tests.rs
  examples/proxy/Cargo.toml
  examples/redirect/client/Cargo.toml
  examples/redirect/client/build.rs
  examples/redirect/client/redirect_client.idl
  examples/redirect/client/src/redirect_client.rs
  examples/redirect/proxy-client/build.rs
  examples/redirect/proxy-client/redirect_proxy_client.idl
  examples/redirect/proxy-client/src/redirect_proxy_client.rs
  examples/redirect/tests/gtest.rs
  examples/rmrk/resource/wasm/Cargo.toml
  examples/rmrk/resource/wasm/build.rs
  examples/rmrk/resource/wasm/rmrk_resource.idl
  examples/rmrk/resource/wasm/src/client.rs
  examples/rmrk/resource/wasm/src/lib.rs
  examples/rmrk/resource/wasm/src/rmrk_resource.rs
  examples/rmrk/resource/wasm/tests/resource_client/mod.rs
  examples/rmrk/resource/wasm/tests/resources.rs
  net/rs/Cargo.lock
  net/rs/Cargo.toml
  net/rs/client-gen/Cargo.toml
  rs/Cargo.toml
  rs/client-gen/Cargo.toml
  rs/client-gen/src/lib.rs
  rs/client-gen/src/root_generator.rs
  rs/client-gen/tests/snapshots/generator__basic_works.snap
  rs/client-gen/tests/snapshots/generator__events_works.snap
  rs/client-gen/tests/snapshots/generator__external_types.snap
  rs/client-gen/tests/snapshots/generator__full.snap
  rs/client-gen/tests/snapshots/generator__full_with_sails_path.snap
  rs/client-gen/tests/snapshots/generator__multiple_services.snap
  rs/client-gen/tests/snapshots/generator__nonzero_works.snap
  rs/client-gen/tests/snapshots/generator__rmrk_works.snap
  rs/ethexe/Cargo.lock
  rs/idl-gen/Cargo.toml
  rs/macros/core/Cargo.toml
  rs/macros/core/src/shared.rs
  rs/sol-gen/Cargo.toml
  rs/src/builder.rs
  rs/src/lib.rs
Labels: rust

#952 feat(client): support to send a message for query with gclient
  examples/demo/app/tests/gclient.rs
  rs/src/gclient/calls.rs
Labels: rust

#986 fix: demo app gclient test
  examples/demo/app/tests/gclient.rs
Labels: A0-pleasereview

#954 perf(macros): use #[sails_rs::event] macro to generate encoding code for event
  Cargo.lock
  Cargo.toml
  examples/demo/app/src/counter/mod.rs
  examples/demo/app/src/dog/mod.rs
  examples/demo/app/src/value_fee/mod.rs
  examples/demo/walker/src/lib.rs
  examples/event-routes/Cargo.toml
  examples/event-routes/app/Cargo.toml
  examples/event-routes/app/build.rs
  examples/event-routes/app/src/lib.rs
  examples/event-routes/tests/gtest.rs
  examples/rmrk/resource/app/src/services/mod.rs
  rs/ethexe/ethapp_with_events/src/lib.rs
  rs/ethexe/macros-tests/tests/snapshots/eth_event__eth_event_basic.snap
  rs/ethexe/macros-tests/tests/snapshots/eth_event__eth_event_indexed.snap
  rs/ethexe/macros-tests/tests/snapshots/eth_event__eth_event_sails_rename.snap
  rs/ethexe/macros-tests/tests/snapshots/service_insta__works_with_allow_attrs.snap
  rs/ethexe/macros-tests/tests/snapshots/service_insta__works_with_basics.snap
  rs/ethexe/macros-tests/tests/snapshots/service_insta__works_with_crate_path.snap
  rs/ethexe/macros-tests/tests/snapshots/service_insta__works_with_docs.snap
  rs/ethexe/macros-tests/tests/snapshots/service_insta__works_with_events.snap
  rs/ethexe/macros-tests/tests/snapshots/service_insta__works_with_export.snap
  rs/ethexe/macros-tests/tests/snapshots/service_insta__works_with_extends.snap
  rs/ethexe/macros-tests/tests/snapshots/service_insta__works_with_extends_and_lifetimes.snap
  rs/ethexe/macros-tests/tests/snapshots/service_insta__works_with_lifetimes_and_events.snap
  rs/ethexe/macros-tests/tests/snapshots/service_insta__works_with_lifetimes_and_generics.snap
  rs/ethexe/macros-tests/tests/snapshots/service_insta__works_with_methods_with_lifetimes.snap
  rs/ethexe/macros-tests/tests/snapshots/service_insta__works_with_reply_with_value.snap
  rs/ethexe/macros-tests/tests/snapshots/service_insta__works_with_special_lifetimes_and_events.snap
  rs/macros/core/src/event/args.rs
  rs/macros/core/src/event/ethexe.rs
  rs/macros/core/src/event/mod.rs
  rs/macros/core/src/lib.rs
  rs/macros/core/src/service/mod.rs
  rs/macros/core/tests/event.rs
  rs/macros/core/tests/snapshots/event__event_basic.snap
  rs/macros/core/tests/snapshots/event__event_sails_rename.snap
  rs/macros/core/tests/snapshots/gservice__works_with_allow_attrs.snap
  rs/macros/core/tests/snapshots/gservice__works_with_basics.snap
  rs/macros/core/tests/snapshots/gservice__works_with_crate_path.snap
  rs/macros/core/tests/snapshots/gservice__works_with_docs.snap
  rs/macros/core/tests/snapshots/gservice__works_with_events.snap
  rs/macros/core/tests/snapshots/gservice__works_with_export.snap
  rs/macros/core/tests/snapshots/gservice__works_with_extends.snap
  rs/macros/core/tests/snapshots/gservice__works_with_extends_and_lifetimes.snap
  rs/macros/core/tests/snapshots/gservice__works_with_lifetimes_and_events.snap
  rs/macros/core/tests/snapshots/gservice__works_with_lifetimes_and_generics.snap
  rs/macros/core/tests/snapshots/gservice__works_with_methods_with_lifetimes.snap
  rs/macros/core/tests/snapshots/gservice__works_with_reply_with_value.snap
  rs/macros/core/tests/snapshots/gservice__works_with_special_lifetimes_and_events.snap
  rs/macros/src/lib.rs
  rs/src/gstd/ethexe.rs
  rs/src/gstd/events.rs
  rs/src/gstd/mod.rs
  rs/src/gstd/services.rs
  rs/src/gstd/utils.rs
  rs/src/prelude.rs
Labels: rust, perf

#982 feat: extend Syscalls with reply and signal details getters
  Cargo.lock
  Cargo.toml
  rs/Cargo.toml
  rs/ethexe/Cargo.lock
  rs/src/gstd/syscalls.rs
  rs/src/prelude.rs
Labels: rust

#989 refactoring(sails-macros-core): Remove `clone` from the `program` macro
  rs/ethexe/macros-tests/tests/snapshots/program_insta__generates_handle_for_multiple_services_with_non_empty_routes.snap
  rs/ethexe/macros-tests/tests/snapshots/program_insta__generates_handle_for_services_with_unwrap_result.snap
  rs/ethexe/macros-tests/tests/snapshots/program_insta__generates_handle_for_single_service_with_non_empty_route.snap
  rs/macros/core/src/program/mod.rs
  rs/macros/core/tests/snapshots/gprogram__generates_async_ctor_with_service.snap
  rs/macros/core/tests/snapshots/gprogram__generates_handle_for_multiple_services_with_non_empty_routes.snap
  rs/macros/core/tests/snapshots/gprogram__generates_handle_for_services_with_unwrap_result.snap
  rs/macros/core/tests/snapshots/gprogram__generates_handle_for_single_service_with_non_empty_route.snap
Labels: A0-pleasereview
